---
title: "A Data Science Breakdown: What Ingredients Are You Tasting in Authentic Japanese Flavors?"
author: "Jingsong Gao (jg2109), Yu Kang (yk685), Chao Li (cl1486), Ercong Luo (el890), Rui Qiu (rq47)"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
---

## Core Network

[Click to view](data_for_viz/01-network/01-network.html).

```{r, message=FALSE, echo=FALSE}
knitr::include_url("data_for_viz/01-network/01-network.html")
```

## Map of Foreign Origins

[Click to view](data_for_viz/02-map/02-map.html).

```{r, message=FALSE, echo=FALSE}
knitr::include_url("data_for_viz/02-map/02-map.html")
```

## Windrose of Ingredients

[Click to view](data_for_viz/03-windrose/windrose.html).

```{r, message=FALSE, echo=FALSE}
knitr::include_url("data_for_viz/03-windrose/windrose.html")
```

## Nutrition Beeswarm

[Click to view](data_for_viz/04-beeswarm/04-beeswarm.html).

```{r, message=FALSE, echo=FALSE}
knitr::include_url("data_for_viz/04-beeswarm/04-beeswarm.html")
```

## Barplot

[Click to view](data_for_viz/05-barplot/).

```{r, message=FALSE, echo=FALSE}
# @TODO
```
